version: "3.4"
services: 
  pgdb: 
    image: postgres:15.6-bullseye
    restart: always
    environment:
      POSTGRES_DB: food
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qazws

    ports: 
      - 5433:5432

    volumes:
      - ./data:/var/lib/postgresql/data

# docker-compose up
 